// SPDX-License-Identifier: Apache-2.0
// Generated by PINE_DUMP_REGISTRY=1 firmware/nrf52840/.build/native/lua-vm.
// Compact session initialization verifies every entry against the Lua declarations.
#pragma once
#include "BotRegistry.h"
namespace onchip {
constexpr BotCommand BotBuiltinCommands[] = {
  {BotCommand::Public, "about", "about", "", "Bot full public key", "!about"},
  {BotCommand::Owner, "admin", "admin", "text?:text:155", "Trusted-owner DM: bot status/help/cancel", "!admin bot status"},
  {BotCommand::Public, "air", "air", "page?:int:1:4", "Scheduler ms/queues/TX counters; not delivery", "!air 2"},
  {BotCommand::Shared, "board", "board", "action:string:6,key?:string:26,text?:text:120", "Target/grant: put KEY TEXT|get KEY|list [PREFIX]|delete KEY", "!@BOTKEY8 board put plan lunch"},
  {BotCommand::Public, "calc", "calc", "expression:text:120", "Decimal + - * / (); depth <=8", "!calc (2+3)*4"},
  {BotCommand::Public, "cancel", "cancel", "id:string:10", "Cancel personal ID; unknown is uncertain TX", "!cancel 1"},
  {BotCommand::Public, "choose", "choose", "options:text:148", "2..8 nonempty | choices; each <=64 bytes", "!choose tea|coffee"},
  {BotCommand::Public, "convert", "convert", "value:string:32,from:string:4,to:string:4", "Case-sensitive units; scalar value; 10 significant digits", "!convert 32 F C"},
  {BotCommand::Public, "forget", "forget", "key:string:32", "Delete private key", "!forget camp"},
  {BotCommand::Public, "help", "help", "name?:string:24,page?:int:1:40", "Commands/arguments; !help PAGE or NAME [PAGE]", "!help remember"},
  {BotCommand::Public, "list-memories", "notes", "prefix?:string:32", "Alias of notes", ""},
  {BotCommand::Public, "mt", "mt", "seconds?:int:1:30", "Observe unique paths; default 5s", "!mt 5"},
  {BotCommand::Public, "neighbors", "neighbors", "page?:int:1:16", "Signed adverts/cached routes; not live adjacency", "!neighbors 2"},
  {BotCommand::Public, "notes", "notes", "prefix?:string:32", "Private keys; narrow prefix if truncated", ""},
  {BotCommand::Public, "path", "path", "", "Received flood path; direct path may be unknown", "!path"},
  {BotCommand::Public, "ping", "ping", "", "Reply Pong", "!ping"},
  {BotCommand::Public, "plugins", "plugins", "page?:int:1:4", "Active source/manifest/modules; shared Lua namespace", "!plugins 2"},
  {BotCommand::Public, "recall", "recall", "key:string:32", "Read private key", "!recall camp"},
  {BotCommand::Public, "remember", "remember", "key:string:32,text:text:120", "Private note; overwrites key", "!remember camp bring tea"},
  {BotCommand::Public, "remind", "remind", "duration:string:10,text:text:120", "DM; grant, trusted time and direct route", "!remind 5m check kettle"},
  {BotCommand::Public, "reminders", "reminders", "", "Personal IDs/states/deadlines; sent is TX only", "!reminders"},
  {BotCommand::Public, "roll", "roll", "dice?:string:24", "[N]dS[+/-K]; default 1d6; <=12d1000 +/-10000", "!roll 2d6+1"},
  {BotCommand::Home, "service", "service", "name:string:7,args?:text:120", "DM/grant; health, echo TEXT or weather PLACE", "!service health"},
  {BotCommand::Public, "signal", "signal", "", "Request RSSI/SNR/path; local reflection marked", "!signal"},
  {BotCommand::Public, "status", "status", "", "Bot readiness, roles and WiFi snapshot", "!status"},
  {BotCommand::Public, "test", "test", "", "Heard path and measured RSSI/SNR; local marked", "!test"},
  {BotCommand::Public, "trace", "trace", "route?:string:154", "TRACE width:hex or heard route", "!trace 1:a1b2"},
  {BotCommand::Public, "uptime", "uptime", "", "Elapsed time since boot", "!uptime"},
  {BotCommand::Public, "version", "version", "", "Native/Lua build; image hash unavailable", "!version"},
  {BotCommand::Home, "weather", "weather", "place?:text:80", "Configured home weather; DM/grant; place required", "!weather Calgary"},
};
constexpr BotManifestView BotBuiltinManifest{BotBuiltinCommands,
  sizeof(BotBuiltinCommands) / sizeof(BotBuiltinCommands[0]),
  sizeof(BotBuiltinCommands) / sizeof(BotBuiltinCommands[0])};
}
