// SPDX-License-Identifier: Apache-2.0
// Generated by tools/product_versions.py; edit release/products.json.
#pragma once

#define MESHCORE_UPSTREAM_VERSION "1.17.1"
#define MESHCORE_UPSTREAM_TAG "companion-v1.17.1"
#define MESHCORE_UPSTREAM_COMMIT "d92964352441e53b93e8667b802e04f6e072b39e"

#define MESHCORE_SLP_ASPEN_VERSION "aspen-0.1.5-rc.1"
#define MESHCORE_SLP_BIRCH_VERSION "birch-0.1.0-rc.1"
#define MESHCORE_SLP_PINE_VERSION "1.17.1-slp-pine"

#ifndef ONCHIP_FIRMWARE_VERSION
#if defined(NRF52_PLATFORM) || defined(NRFMAST_RF_ENABLED)
#define ONCHIP_FIRMWARE_VERSION MESHCORE_SLP_PINE_VERSION
#else
#define ONCHIP_FIRMWARE_VERSION MESHCORE_SLP_ASPEN_VERSION
#endif
#endif

static_assert(sizeof(ONCHIP_FIRMWARE_VERSION) <= 20,
              "Firmware profile must fit the companion device-info version field");
static_assert(sizeof(MESHCORE_SLP_BIRCH_VERSION) <= 20,
              "Birch identity must fit the companion device-info version field");
