cmake_minimum_required(VERSION 3.16)
project(meshcore_wamr C)
set(WAMR_BUILD_INTERP 1)
set(WAMR_BUILD_FAST_INTERP 0)
set(WAMR_BUILD_AOT 0)
set(WAMR_BUILD_JIT 0)
set(WAMR_BUILD_FAST_JIT 0)
set(WAMR_BUILD_LIBC_BUILTIN 0)
set(WAMR_BUILD_LIBC_WASI 0)
set(WAMR_BUILD_MULTI_MODULE 0)
set(WAMR_BUILD_SIMD 0)
set(WAMR_BUILD_REF_TYPES 0)
set(WAMR_BUILD_BULK_MEMORY 0)
set(WAMR_BUILD_SHARED_MEMORY 0)
set(WAMR_BUILD_THREAD_MGR 0)
set(WAMR_BUILD_MEMORY64 0)
set(WAMR_BUILD_GC 0)
set(WAMR_BUILD_TAIL_CALL 0)
set(WAMR_BUILD_INSTRUCTION_METERING 1)
add_definitions(-DWASM_ENABLE_LABELS_AS_VALUES=0)
set(WAMR_DISABLE_HW_BOUND_CHECK 1)
set(WAMR_DISABLE_STACK_HW_BOUND_CHECK 1)
set(WAMR_BUILD_MINI_LOADER 0)
set(WAMR_BUILD_LOAD_CUSTOM_SECTION 0)
set(WAMR_BUILD_SHRUNK_MEMORY 0)
include(${WAMR_ROOT_DIR}/build-scripts/runtime_lib.cmake)
add_library(meshcore_wamr STATIC ${WAMR_RUNTIME_LIB_SOURCE})
get_directory_property(includes INCLUDE_DIRECTORIES)
get_directory_property(defines COMPILE_DEFINITIONS)
file(WRITE "${CMAKE_BINARY_DIR}/sources.txt" "${WAMR_RUNTIME_LIB_SOURCE}")
file(WRITE "${CMAKE_BINARY_DIR}/includes.txt" "${includes}")
file(WRITE "${CMAKE_BINARY_DIR}/defines.txt" "${defines}")
