// SPDX-License-Identifier: Apache-2.0
// Code generated by tools/product_versions.py; DO NOT EDIT.
package buildinfo

const (
	Profile = "birch"
	ProductVersion = "0.1.0-rc.1"
	HostVersion = "birch-0.1.0-rc.1"
	MeshCoreReference = "1.17.1"
	MeshCoreTag = "companion-v1.17.1"
	MeshCoreCommit = "d92964352441e53b93e8667b802e04f6e072b39e"
)
