#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate firmware/host identities from the product release authority."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SEMVER = re.compile(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-rc\.([1-9][0-9]*))?\Z")


def load(root=ROOT):
    data = json.loads((root / "release/products.json").read_text())
    if data["schema_version"] != 1 or set(data["products"]) != {"aspen", "birch", "pine", "willow"}:
        raise ValueError("Expected Aspen, Birch, Pine and Willow release schema 1")
    upstream = data["upstream"]
    if not re.fullmatch(r"[0-9a-f]{40}", upstream["commit"]):
        raise ValueError("Upstream commit must be a full lowercase Git SHA")
    if not SEMVER.fullmatch(upstream["version"]) or upstream["tag"] != "companion-v" + upstream["version"]:
        raise ValueError("Upstream tag/version mismatch")
    for name, product in data["products"].items():
        version = product["version"]
        if not SEMVER.fullmatch(version):
            raise ValueError(f"Invalid {name} release version")
        if len(identity(name, version).encode("ascii")) > 19:
            raise ValueError(f"{name} identity exceeds the companion field (19 bytes plus NUL)")
    if data["compatibility"] != {"queued_phy": 1, "native_worker": 1, "companion": 13,
                                  "dashboard_api": 1, "wasm_application_abi": 1}:
        raise ValueError("Protocol versions must match the current wire contracts")
    return data


def identity(name, version):
    return f"{name}-{version}"


def tag(name, version):
    return f"{name}-v{version}"


def display(name, version, upstream):
    number, separator, rc = version.partition("-rc.")
    return f"{name.title()} {number}" + (f" RC{rc}" if separator else "") + f" · based on MeshCore {upstream}"


def generated(data):
    upstream = data["upstream"]
    products = data["products"]
    header = '// SPDX-License-Identifier: Apache-2.0\n// Generated by tools/product_versions.py; edit release/products.json.\n#pragma once\n\n'
    header += f'#define MESHCORE_UPSTREAM_VERSION "{upstream["version"]}"\n'
    header += f'#define MESHCORE_UPSTREAM_TAG "{upstream["tag"]}"\n'
    header += f'#define MESHCORE_UPSTREAM_COMMIT "{upstream["commit"]}"\n\n'
    for name, product in products.items():
        header += f'#define MESHCORE_SLP_{name.upper()}_VERSION "{identity(name, product["version"])}"\n'
    header += "\n"
    header += '''#ifndef ONCHIP_FIRMWARE_VERSION
#if defined(NRF52_PLATFORM) || defined(NRFMAST_RF_ENABLED)
#define ONCHIP_FIRMWARE_VERSION MESHCORE_SLP_PINE_VERSION
#else
#define ONCHIP_FIRMWARE_VERSION MESHCORE_SLP_ASPEN_VERSION
#endif
#endif

static_assert(sizeof(ONCHIP_FIRMWARE_VERSION) <= 20,
              "Firmware profile must fit the companion device-info version field");
static_assert(sizeof(MESHCORE_SLP_BIRCH_VERSION) <= 20,
              "Birch identity must fit the companion device-info version field");
'''
    birch = products["birch"]["version"]
    go = f'''// SPDX-License-Identifier: Apache-2.0
// Code generated by tools/product_versions.py; DO NOT EDIT.
package buildinfo

const (
\tProfile = "birch"
\tProductVersion = "{birch}"
\tHostVersion = "{identity("birch", birch)}"
\tMeshCoreReference = "{upstream["version"]}"
\tMeshCoreTag = "{upstream["tag"]}"
\tMeshCoreCommit = "{upstream["commit"]}"
)
'''
    make = f'''# Generated by tools/product_versions.py; edit release/products.json.
MESHCORE_RELEASE_REF := {upstream["tag"]}
MESHCORE_RELEASE_SHA := {upstream["commit"]}
'''
    willow = products["willow"]["version"]
    hew = f'''//! Generated by tools/product_versions.py; edit release/products.json.
pub fn version() -> string {{ "{willow}" }}
'''
    python = f'''# SPDX-License-Identifier: Apache-2.0
# Generated by tools/product_versions.py; edit release/products.json.
VERSION = "{willow}"
'''
    return {"firmware/esp32/FirmwareIdentity.h": header,
            "internal/buildinfo/identity.go": go, "release/versions.mk": make,
            "experiments/hew-roles/release_identity.hew": hew,
            "experiments/hew-roles/release_identity.py": python}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Refuse stale generated identities")
    args = parser.parse_args()
    for path, content in generated(load()).items():
        target = ROOT / path
        if args.check:
            if not target.exists() or target.read_text() != content:
                parser.error(f"{path} is stale; run python3 tools/product_versions.py")
        else:
            target.write_text(content)


if __name__ == "__main__":
    main()
