#pragma once

#define KISS_FEND 0xC0
#define KISS_FESC 0xDB
#define KISS_TFEND 0xDC
#define KISS_TFESC 0xDD
#define KISS_MAX_FRAME_SIZE 512
#define KISS_MAX_PACKET_SIZE 255
#define KISS_MAX_ENCODED_FRAME_SIZE 1030
#define KISS_HW_MAX_PAYLOAD_SIZE 513
#define KISS_CMD_DATA 0x00
#define KISS_CMD_SETHARDWARE 0x06
#define HW_CMD_SET_SIGNAL_REPORT 0x19
#define HW_CMD_GET_SIGNAL_REPORT 0x1A
#define HW_RESP(cmd) ((cmd) | 0x80)
#define HW_RESP_ERROR 0xF1
#define HW_RESP_TX_DONE 0xF8
#define HW_RESP_RX_META 0xF9
#define HW_ERR_INVALID_LENGTH 0x01
#define HW_ERR_TX_BUSY 0x07
